Repository adityadomle/BizFlow, pull requests merged in 2025-09, with the labels that each got.

#323 Fix color mismatch and add smooth GSAP animations
  src/pages/LeaderBoard.jsx
Labels: GSSoC25, Level 3

#334 Fixed About link in footer to redirect to About page.
  src/components/Footer.jsx
Labels: GSSoC25, Level 1

#336 Add additional point to Time schedule section
  src/components/ScheduleSection.jsx
Labels: GSSoC25, Level 3

#341 [FIX]: #324 Become a Partner Page – Hover Effects Too Bouncy & Page Load Cuts Off Heading
  src/pages/Partner.jsx
Labels: GSSoC25, Level 3

#347 Expand purpose section with two additional boxes
  src/components/PurposeSection.jsx
Labels: GSSoC25, Level 3

#360 Changing the text colour of sime buttons while hovering
  src/components/FAQ.jsx
  src/components/FeaturesSection.jsx
  src/components/Footer.jsx
  src/components/ScheduleSection.jsx
  src/components/ServicesSection.jsx
Labels: GSSoC25, Level 2

#365 improved the ui of the button making it more cleaner
  src/components/Navbar.jsx
Labels: GSSoC25, Level 1

#369 Fixed Active State & Hover Effects for Community Tab
  src/components/Navbar.jsx
Labels: GSSoC25, Level 2

#371 Fix: corrected extra margin issue in about page hero section
  src/pages/About.jsx
Labels: GSSoC25, Level 1

#378 Fix: correct UI issues on Home page.
  src/components/Footer.jsx
  src/components/NewsletterSection.jsx
Labels: GSSoC25, Level 2

#368 Revamp "How can we help your business?" Section
  src/components/FeaturesSection.jsx
Labels: GSSoC25, Level 3, Ui Ux

#379 Enhence Color contrast of back to top button
  src/components/ScrollToTop.tsx
Labels: GSSoC25, Level 1

#386 [FIX]: #382 Navigation Bar is Compressed on Larger Viewports
  src/components/Navbar.jsx
Labels: GSSoC25, Level 2

#398 Added hover animation to the boxes on the about section
  src/pages/About.jsx
Labels: GSSoC25, Level 2

#424 Solved Bug: Weird Animation #210
  src/components/Hero.jsx
  src/components/Loader.jsx
Labels: GSSoC25, Level 2

#408 Add workflow to comment on merged pull requests
  .github/workflows/pr-merge-automate-message.yml
Labels: GSSoC25, Level 3

#418 Shadow hover animation added on the about section
  src/pages/About.jsx
Labels: GSSoC25, Level 1

#429 fix dark mode btn rotation angle on toggling
  src/components/Navbar.jsx
Labels: GSSoC25, Level 1
