Repository adityadomle/BizFlow, pull requests merged in 2025-08, with the labels that each got.

#32 Feature Request: Add "BizFlow" to Title and Navbar
  index.html
  src/components/Navbar.jsx
Labels: GSSoC25, Level 1

#38 Add visitor analytics and admin dashboard for user engagement tracking
  .gitignore
  ANALYTICS_IMPLEMENTATION_SUMMARY.md
  ANALYTICS_SETUP.md
  CONTRIBUTOR_ANALYTICS_SETUP.md
  env.example
  index.html
  package.json
  src/App.jsx
  src/components/AnalyticsDashboard.jsx
  src/components/FeaturesSection.jsx
  src/components/Hero.jsx
  src/components/Navbar.jsx
  src/config/analytics.js
  src/utils/analytics.js
  src/utils/useScrollTracking.js
  src/utils/useTimeTracking.js
Labels: GSSoC25, Level 3

#73 Feature/Added-tour-Guide-For-first-time-Users (#51)
  package-lock.json
  package.json
  src/App.jsx
  src/components/FeaturesSection.jsx
  src/components/Hero.jsx
  src/components/Navbar.jsx
  src/components/NewsletterSection.jsx
  src/components/PricingSection.jsx
  src/components/ServicesSection.jsx
  src/components/TestimonialsSection.jsx
  src/components/UserTourGuide.jsx
Labels: GSSoC25, Level 3

#103 Convert Testimonials section into an auto-scrolling carousel
  src/App.jsx
  src/components/Navbar.jsx
  src/components/TestimonialsSection.jsx
  src/index.css
Labels: GSSoC25, Level 3

#98 [FIX]: #76 Lighter Button & Background Colors
  src/components/FeaturesSection.jsx
  src/components/PricingSection.jsx
  src/components/ServicesSection.jsx
Labels: GSSoC25, Level 1

#104 adding icon
  src/components/Contact.jsx
Labels: GSSoC25, Level 2

#111 Fix/tailwind sm px6
  package-lock.json
  src/App.jsx
  src/components/FeaturesSection.jsx
  src/index.css
  tailwind.config.js
Labels: GSSoC25, Level 2

#122 [FIX]: #80 Navbar Layout Issue on Medium Screen Sizes
  src/components/Navbar.jsx
Labels: GSSoC25, Level 2

#216 Enhanced the Parter section (Companies) for dark and light themes
  package-lock.json
  src/components/CompanyLogo.jsx
Labels: GSSoC25, Level 2

#217 Testimonial fixed with New UI
  src/components/TestimonialsSection.jsx
Labels: enhancement, GSSoC25, Level 3, Ui Ux

#221 Fixed the responsiveness issue in navbar
  src/App.jsx
  src/components/FloatingThemeToggle.jsx
  src/components/Navbar.jsx
Labels: GSSoC25, Level 3

#228 Removed Analytics Page and all the related links
  src/App.jsx
  src/components/AnalyticsDashboard.jsx
  src/components/Navbar.jsx
Labels: GSSoC25, Level 3

#245 Made the Contributor's page a bit more Professional
  src/pages/Contibutors.jsx
Labels: GSSoC25, Level 3

#247 FAQ and Newsletter section
  src/components/FAQ.jsx
  src/components/Hero.jsx
  src/components/NewsletterSection.jsx
Labels: GSSoC25, Level 3

#248 contact us page
  src/components/Contact.jsx
Labels: GSSoC25, Level 3

#256 [FIX]: #251 UI Issues on Home Page
  src/components/Hero.jsx
  src/components/Navbar.jsx
  src/index.css
Labels: GSSoC25, Level 3

#265 Added a new page as contributorGuide
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/ContributorGuide.jsx
Labels: enhancement, GSSoC25, Level 3

#273 I have improved the button to top icon
  src/components/ScrollToTop.tsx
Labels: bug, GSSoC25, Level 1

#275 Implemented Lazy Loading and Loader to Improve Performance
  src/App.jsx
  src/components/Navbar.jsx
Labels: GSSoC25, Level 3

#276 Enhanced README.md with Project Ideas, Theme, Contributor Guide & Visual Appeal
  README.md
Labels: documentation, GSSoC25, Level 1

#281 Add GitHub Stats Section
  package-lock.json
  package.json
  src/pages/Contibutors.jsx
  src/pages/GitHubStats.jsx
Labels: GSSoC25, Level 3

#279 Fix : Mobile Navbar Responsiveness and Add Scroll Lock with Close Button
  src/components/Navbar.jsx
Labels: bug, GSSoC25, Level 2

#286 [FIX]: #250 Navigation, Email, and UI Issues in the "Still Have Questions" Section
  src/components/FAQ.jsx
Labels: GSSoC25, Level 3

#285 Added a new loader
  src/App.jsx
  src/components/Loader.jsx
  src/pages/Contibutors.jsx
Labels: enhancement, GSSoC25, Level 3

#284 Enhancement of Navbar animations and Hamburger menu
  src/components/Navbar.jsx
Labels: GSSoC25, Level 3

#282 Consolidate docs into README & add .env.example
  .env.example
  ANALYTICS_IMPLEMENTATION_SUMMARY.md
  ANALYTICS_SETUP.md
  CODE_OF_CONDUCT.md
  CONTACT_SETUP.md
  CONTRIBUTING.md
  CONTRIBUTOR_ANALYTICS_SETUP.md
  README.md
Labels: GSSoC25, Level 3

#290 Add Dynamic GSSoC'25 Leaderboard
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/LeaderBoard.jsx
Labels: GSSoC25, Level 3

#300 Added the Email verification, Color code and Glassmorphism
  src/components/Hero.jsx
Labels: GSSoC25, Level 3, Ui Ux

#294 Fixed the clipping of the Pricing Plans
  src/components/PricingSection.jsx
Labels: GSSoC25, Level 2, Ui Ux

#307 Pricing section
  package-lock.json
  package.json
  src/components/PricingSection.jsx
Labels: GSSoC25, Level 3

#305 Leaderboard enhanced
  .env.example
  src/pages/LeaderBoard.jsx
Labels: GSSoC25, Level 3

#306 Enhancement: Partner Form UI/UX Improvements (Light + Dark Mode)
  src/pages/Partner.jsx
Labels: GSSoC25, Level 3

#310 Add pull request template
  .github/pull_request_template.md
Labels: GSSoC25, Level 3

#313 redesined backtotop button
  src/components/ScrollToTop.tsx
Labels: GSSoC25, Level 1, Ui Ux

#317 Enhance Contributors Page with GSAP ScrollTrigger Animations
  package-lock.json
  package.json
  src/pages/Contibutors.jsx
  src/pages/GitHubStats.jsx
Labels: GSSoC25, Level 3

#315 UI Enhancement: Color Code Management and Animated Bouncing Elements
  src/pages/Partner.jsx
Labels: GSSoC25, Level 3

#316 Enable blank issues in issue template configuration
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug, GSSoC25, Level 2
